menu:
    Blog: /
    Archive: /archives/
    Mothership: https://bensarmiento.com
    Rss: /atom.xml

favicon: /ben-sketch-green.png
logo: /ben-sketch-green.png

# Comment
# e.g disqus: seansun
disqus: 
duoshuo: 

# Analytics
# google-analytics:
ga: UA-80507391-2

# Copyright Infomation
startyear: 2016

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: true
